### ISSUE TITLE
 Invalid version: 'RegionCLIP'

### ISSUE THREAD

**Issue by pinyaras** [microsoft/RegionCLIP#58]
Obtaining file:///home/lab/dev/RegionCLIP
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      /home/lab/anaconda3/envs/regionclip/lib/python3.9/site-packages/setuptools/dist.py:543: UserWarning: The version specified ('RegionCLIP') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
        warnings.warn(
      running egg_info
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/lab/dev/RegionCLIP/setup.py", line 193, in <module>
          setup(
        File "/home/lab/anaconda3/envs/regionclip/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/lab/anaconda3/envs/regionclip/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/lab/anaconda3/envs/regionclip/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/lab/anaconda3/envs/regionclip/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/lab/anaconda3/envs/regionclip/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/lab/anaconda3/envs/regionclip/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/home/lab/anaconda3/envs/regionclip/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/home/lab/anaconda3/envs/regionclip/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
          parsed_version = parse_version(self.egg_version)
        File "/home/lab/anaconda3/envs/regionclip/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'RegionCLIP'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip

**Comment by YiwuZhong** [comment]
Please refer to issue #60. The solution is to downgrade the version of setuptools: `pip install setuptools==59`

**Comment by Mukil07** [comment]
If it doesnt work, try replacing the ` version=get_version()` --> `version='0.1.0'` in line 195 of setup.py
