### ISSUE TITLE
NaN Loss

### ISSUE THREAD

**Issue by drahmad89** [microsoft/RegionCLIP#7]
Hello,

During training the detector on my own, the training was interrupted due to NaN loss encounter. The following is the Traceback I got:

[07/12 01:10:03 d2.utils.events]:  eta: 1:41:36  iter: 4299  total_loss: 0.1065  loss_cls: 0.02696  loss_box_reg: 0.07967  time: 1.2804  data_time: 0.0020  lr: 0.002  max_mem: 15826M
ERROR [07/12 01:10:18 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/ahmad/RegionCLIP/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/ahmad/RegionCLIP/detectron2/engine/defaults.py", line 506, in run_step
    self._trainer.run_step()
  File "/home/ahmad/RegionCLIP/detectron2/engine/train_loop.py", line 287, in run_step
    self._write_metrics(loss_dict, data_time)
  File "/home/ahmad/RegionCLIP/detectron2/engine/train_loop.py", line 329, in _write_metrics
    raise FloatingPointError(
FloatingPointError: Loss became infinite or NaN at iteration=4311!
loss_dict = {'loss_cls': nan, 'loss_box_reg': nan}
[07/12 01:10:18 d2.engine.hooks]: Overall training speed: 4309 iterations in 1:31:58 (1.2806 s / it)
[07/12 01:10:18 d2.engine.hooks]: Total training time: 1:37:23 (0:05:25 on hooks)
[07/12 01:10:18 d2.utils.events]:  eta: 1:41:16  iter: 4311  total_loss: 0.1009  loss_cls: 0.02645  loss_box_reg: 0.07499  time: 1.2803  data_time: 0.0020  lr: 0.002  max_mem: 15826M
Traceback (most recent call last):
  File "/home/ahmad/RegionCLIP/./tools/train_net.py", line 170, in <module>
    launch(
  File "/home/ahmad/RegionCLIP/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/home/ahmad/RegionCLIP/./tools/train_net.py", line 164, in main
    return trainer.train()
  File "/home/ahmad/RegionCLIP/detectron2/engine/defaults.py", line 496, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/ahmad/RegionCLIP/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/ahmad/RegionCLIP/detectron2/engine/defaults.py", line 506, in run_step
    self._trainer.run_step()
  File "/home/ahmad/RegionCLIP/detectron2/engine/train_loop.py", line 287, in run_step
    self._write_metrics(loss_dict, data_time)
  File "/home/ahmad/RegionCLIP/detectron2/engine/train_loop.py", line 329, in _write_metrics
    raise FloatingPointError(
FloatingPointError: Loss became infinite or NaN at iteration=4311!
loss_dict = {'loss_cls': nan, 'loss_box_reg': nan}

**Comment by YiwuZhong** [comment]
Hi @drahmad89, thanks for your interests. It is hard to debug by simply looking at the error report. Can you post the command line you run?

**Comment by drahmad89** [comment]
This is the command used, to note that it went through the first coco evalution and in the second epoch i got the issue:

python ./tools/train_net.py --num-gpus 2 --config-file ./configs/HUMANWARE-InstanceDetection/CLIP_fast_rcnn_R_50_C4_Humanware.yaml  MODEL.WEIGHTS ./pretrained_ckpt/regionclip/regionclip_pretrained-cc_rn50.pth MODEL.CLIP.OFFLINE_RPN_CONFIG ./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x_ovd_FSD.yaml  MODEL.CLIP.BB_RPN_WEIGHTS ./pretrained_ckpt/rpn/rpn_coco_48.pth MODEL.CLIP.TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/Humanware_indoor6_RN50x64.pth MODEL.CLIP.OPENSET_TEST_TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/Humanware_indoor6_RN50x64.pth

**Comment by Jawing** [comment]
Is it possible to add a feature/config to save the model `model_final.pth` at each evaluation during training (if the model has better AP, non-overfitting) rather than saving it at the end of the training loop? As well as resuming training from the iteration where it encountered the NaN Loss. Usually, the nan loss happens before the model is saved and changing the learning rate does alleviate the problem, although it isn't a guarantee that it won't happen, therefore resuming the training from the previously saved model with a lower learning rate would be helpful!

**Comment by YiwuZhong** [comment]
Detectron2 has already supported (1) saving checkpoints for a few iterations (setting [`SOLVER.CHECKPOINT_PERIOD`](https://github.com/microsoft/RegionCLIP/blob/a4d99b239983f901ca2f9bcab0867df29fa7ea68/detectron2/config/defaults.py#L655)) and (2) resuming training (adding `--resume` in command line).

**Comment by zhangxgu** [comment]
I meet this problem too on my own dataset. It seems the total loss is less than 0.001 after 20000 iters. ORZ
