### ISSUE TITLE
Version 'RegionCLIP' is not valid according to PEP 440.

### ISSUE THREAD

**Issue by lanternjx** [microsoft/RegionCLIP#71]
I can not install the setup.py

and it's the error:

(regionclip) wangjingxian@yuhong-PowerEdge-T630:~/pycode$ python -m pip install -e RegionCLIP-main
Obtaining file:///data/wangjingxian/pycode/RegionCLIP-main
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/data/wangjingxian/cuda/cuda113'
      /data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/dist.py:520: SetuptoolsDeprecationWarning: Invalid version: 'RegionCLIP'.
      !!
      
              ********************************************************************************
              The version specified is not a valid version according to PEP 440.
              This may not work as expected with newer versions of
              setuptools, pip, and PyPI.
      
              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************
      
      !!
        self._validate_version(self.metadata.version)
      running egg_info
      /data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/command/egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: 'RegionCLIP'.
      !!
      
              ********************************************************************************
              Version 'RegionCLIP' is not valid according to PEP 440.
      
              Please make sure to specify a valid version for your package.
              Also note that future releases of setuptools may halt the build process
              if an invalid version is given.
      
              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************
      
      !!
        return _normalization.best_effort_version(tagged)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/wangjingxian/pycode/RegionCLIP-main/setup.py", line 193, in <module>
          setup(
        File "/data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
          parsed_version = packaging.version.Version(self.egg_version)
        File "/data/wangjingxian/conda/envs/regionclip/lib/python3.9/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'RegionCLIP'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by YiwuZhong** [comment]
Please refer to issue #60. The solution is to downgrade the version of setuptools: pip install setuptools==59
